### ISSUE TITLE
On-Screen Keyboard

### ISSUE THREAD

**Issue by IonutCicio** [Prometal328/Keyboard-Teacher#14]
As arleady said in the user stories, I would like to create an on-screen keyboard. I'm working on the class key. The problem is figuring out how to instantiate about 60 object. Would it be advantageous to create an array? Is there another better way?

**Comment by wbigger** [comment]
An array is a good choice. Your implementation until now is fine and I suggest you continue on this way.

Out of curiosity, other ways are:
- [ArrayList](https://processing.org/reference/ArrayList.html), useful for dynamically changing lists (not your case)
- Dictionaries (for example [StringDict](https://processing.org/reference/StringDict.html)), to access an element of an array using an user-defined String key instead of the integer index
- [HashMap](https://processing.org/reference/HashMap.html), a generalization of dictionaries, where you can access an element of any type of array with any type of key (much more complex to use)
