### ISSUE TITLE
Adding "current mode" text to main menu and settings menu

### ISSUE THREAD

**Issue by IonutCicio** [Prometal328/Keyboard-Teacher#21]
I thought it would be useful to display what is the current mode the program is setted: hard, normal or easy.

**Comment by wbigger** [comment]
Absolutely agree.

This kind of reasoning usually happens in the wireframe phase, before implementation. Indeed, is one of the main reason for making wireframes: printing them, drawing with pencil on them, showing them to your parents, grandparents, siblings, neighbors, friends, cats, dogs, or whatever in order to reasoning on them!

**Comment by IonutCicio** [comment]
Also adding a "current user" could be useful on the start menu.
