### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by IonutCicio** [Prometal328/Keyboard-Teacher#23]
### ***These are some ideas to improve the project:***
* **Show all the data in the *"textToWriteBox"* at the end of the exercise.**
* **In *"normal"* and *"easy"* mode, the next key to press will be highlighted.**
* **Adding possibility to *"change language"*: italian or english.**
* **Adding possibility to *"change software's colors"*.**
* **When *"startMenu"* is opened, if it's in *"easy"* or *"normal"* mode, there will be shown two hands positionated on the keys, to show what fingers to use.**
* **Adding *"reset Exercise button"*.**
* **Changing time's format from *seconds*, to *minutes:seconds*.**
* ***SUGGESTION* change text dimension in settings (big, small, medium).**
* **Adding my name, github repository link, and my email to the project, in main menu.**
* ***Remember to add sounds.***
* ***Adding mediafire download (or something like that) at the end of the work***

**Comment by wbigger** [comment]
I suggest to rewrite the ideas as stories, or tasks within stories, because
in the current text it is not clear why these ideas should improve the
project, who benefits from these ideas and, therefore, which one should be
implemented (if any) and in which order.

To frame tasks into stories is important also if these are personal notes,
because in a short time you will probably forget a lot of things about them.
